### ISSUE TITLE
Issues logging in with the sandbox

### ISSUE THREAD

**Issue by Akm0d** [FamilySearch/mobile-android-sample#8]
I want to be able to see the TreeActivity, but getting a token always fails.  I got an API Key and a sandbox username and password.  They all seem to work when I tested OAuth with fiddle, but I can't get it working inside the app.

**Comment by misbach** [comment]
Do you have any other details that can help us narrow down the steps to duplicate the problem?

**Comment by lkazandzhi** [comment]
See https://groups.google.com/a/ldsmail.net/forum/#!topic/fsdn/GxH5ILBiYa8 for a solution.
