### ISSUE TITLE
Can't login to the app

### ISSUE THREAD

**Issue by michelesalvador** [FamilySearch/mobile-android-sample#9]
These are my steps:
- Create an account at [familysearch.org/developers](https://www.familysearch.org/developers/).
Create a new App to obtain an App Key (an 18 digits alpha-numeric string).
Put `http://fiddle.jshell.net` as Redirect URI.
At step _2 App In Development_ click "Done".
At step _3 Review Compatibility_  **don't** click "Apply for Compatible Review".

- In the [Test OAuth2 JS Fiddle](http://jsfiddle.net/familysearchdevelopers/as56e/) put the App Key.
Run the code.
Login with username and password of Integration (Sandbox) account.
Successfully receive an Access token.

- From GitHub download _FamilySearch/mobile-android-sample_.
Unzip and open in Android Studio 3.1.
Android Studio automatically downloads all the Gradle, Android SDK Platform 23 and Build Tools.
JDK 8 is already installed.
Create the `AppKeys.java` class and put the App Key in.
Successfully run _FamilySearch Android Sample App_ in a smartphone.

- In the smartphone try to login to the app with the Sandbox account, and also with my FamilySearch account, and the developer account...

The result is always that is **impossible to login to the app**, with a message:
> Error getting the token. Check username and password

Meanwhile Android Studio Logcat writes:
>I/PhoneWindow: [generateLayout] setColorNavigationBar => color=0x ff000001
D/PhoneWindowEx: Ex5. SystemProperties.get(KEY) result is NULL!!
D/libc-netbsd: [getaddrinfo]: hostname=xxxxx; servname=(null); cache_mode=(null), netid=0; mark=0
    [getaddrinfo]: ai_addrlen=0; ai_canonname=xxxxx; ai_flags=4; ai_family=0
    [getaddrinfo]: hostname=xxxxx; servname=(null); cache_mode=(null), netid=0; mark=0
    [getaddrinfo]: ai_addrlen=0; ai_canonname=xxxxx; ai_flags=1024; ai_family=0
I/System.out: propertyValue:false
E/CliptrayUtils: hideClipTrayIfNeeded() TextView is focused!! hideClipTray()

Am I doing something wrong?

**Comment by misbach** [comment]
@michelesalvador What is your api key, and what reference are you pointing to (production, beta, or integration)?

**Comment by michelesalvador** [comment]
After 2 years I tried it all over again and I have the same problem to access the app:
> Error getting the token. Check username and password

My app key is **a02f100000TbGjEAAV**

In my FamilySearch developer page under _Integration (Sandbox) Account_ the URL is https://integration.familysearch.org

**Comment by misbach** [comment]
Hi @michelesalvador, sorry to hear of the trouble. Not sure what the problem is without stepping through the code myself. Keep in mind that this project isn't supported any longer. If it helps you see a working authentication scenario working on this github page. https://github.com/misbach/fs-auth

**Comment by michelesalvador** [comment]
Thank you for the answer.

Meantime I have found how to login with an integration account.
In `Utilities.java` line 40 you have to put another URL:
"https://integration.familysearch.org/platform/collection" or "https://api-integ.familysearch.org/platform/collection".
Like this you can access to the app.

But after that in `TreeServices.getAncestryTree()` the server answer with a 400 response..
